### ISSUE TITLE
Add flag to obscure personal information for GDPR compliance

### ISSUE THREAD

**Issue by MarcBuch** [grafana/okta-logs-collector#8]
Heyo!

I would love to use this tool, yet it is required that personal information, like actor.alternateId, actor.displayName is redacted. Therefore I propose a flag called `--gdpr` or something that can redact this information to `"displayName": "P...r",`.

To be redacted:

- actor.alternateId
- actor.displayName
- target.alternateId
- target.displayName

If this gets approval, I can also implement it. I already have working implementation on my local machine.

**Comment by mostafa** [comment]
Sounds good to me! Go for it.

**Comment by kelnage** [comment]
This sounds like a great feature, but I'm not sure about calling it `--gdpr` - perhaps something along the lines of `--sanitize-user-identity`?
